### ISSUE TITLE
Could not connect to eris-keys server

### ISSUE THREAD

**Issue by dave-ct** [eris-ltd/eris-cli#762] opened 2016-06-20 13:03 UTC
Please include in your bug report:

DOCKER Version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Eris CLI Version: 0.12.0

Using OSX

So have followed the getting started with Eris guide. Docker is running. When I run "eris services start keys" the docker container seems to start so I then run "eris chains make test_chain --chain-type simplechain".  This command fails with the following:

iMac:.eris dave$ eris chains make test__chain --chain-type simplechain
Could not connect to eris-keys server. Start it with `eris services start keys`. Error: Post http://keys:4767/gen: dial tcp 81.200.64.50:4767: i/o timeout
Container interactive-a8792992-9326-476f-9965-2993f4f8f5a2 exited with status 1

Please can you advise this?

**Comment by rguikers** [comment] 2016-07-01 07:20
FYI, this happened for me with docker version 12 rc2 on Mac. Currently running it with docker 1.10.3 without problems. Seems that binding to 0.0.0.0 was pointing to my gateway address on my machine (with the latest docker version)

**Comment by pietv** [comment] 2016-07-01 07:24
@dave-ct @rguikers please kindly refrain from using the Docker for Mac version 0.12.0-rc2. This error `dial tcp ... timeout` or `dial udp ... timeout` do happen for some people. Currently it's an open issue on the Docker side https://github.com/docker/docker/issues/23792, waiting for a fix or a workaround. Thanks.

**Comment by rguikers** [comment] 2016-07-01 10:05
Thanks, this was the reason to go back to version 1.10.. Just mentioning it because it sounds like a similar problem..

**Comment by zramsay** [comment] 2016-07-03 21:10
Hi @dave-ct can you confirm this was happening on `docker version 1.11.2` and not `1.12.0-rc2`. The latter version is known to break eris (see #780) but should work on 1.11.2. If not using Docker for Mac, can you try restarting your docker-machine?

**Comment by dave-ct** [comment] 2016-07-04 06:37
@zramsay this is happening on 1.11.2 on Mac.  My internet provider does have a host called "keys" which has an internal DNS entry 81.200.64.50 on their DNS servers which I suspect is causing the issue. Have tried adding a local host entry to point it back at the right IP but looks like when it starts keys it does not call the local host file and gets the IP from DNS/bind. This on Virgin Media in the uk.  I have a colleague who is on a different provider and they don't get the issue and their provider can not resolve "keys" on DNS.

**Comment by dave-ct** [comment] 2016-07-04 06:41
@zramsay I will try changing to point DNS to google's DNS servers instead of Virgin Media's ones tonight to see if that can be used as a workaround.

**Comment by zramsay** [comment] 2016-07-04 15:38
ah, yes, that could definitely cause problem. Interested to see how your work-a-round will go. I'm trying to think of a work-a-round by hacking `eris` but it would be far from elegant.

**Comment by dave-ct** [comment] 2016-07-04 16:22
Hi @zramsey , changing DNS server to 8.8.8.8 worked.

**Before:**
```
iMac:~ dave$ nslookup keys
Server:		192.168.0.1
Address:	192.168.0.1#53
Non-authoritative answer:
Name:	keys
Address: 81.200.64.50
```

**FIX**
Updated /etc/resolv.conf to
`nameserver 8.8.8.8`

Also need to update in the the network setting under preferences

![osx_dns-change](https://cloud.githubusercontent.com/assets/17012929/16566292/128341da-420b-11e6-9f7b-07cfcc3d3674.png)

Checked resolution of keys again

```
iMac:~ dave$ nslookup keys
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find keys: NXDOMAIN
```

No longer resolving keys to an external IP address

Tried to start keys service again and get a chain running. all good :-)


```
iMac:~ dave$ eris services start keys
iMac:~ dave$ eris chains make test_chain --chain-type simplechain
iMac:~ dave$ eris services ls -a
SERVICE     ON     CONTAINER ID     DATA CONTAINER     IMAGE                        COMMAND                                       PORTS
keys        *      72c3c36c86       cc8dd6bf85         quay.io/eris/keys:0.12.0     [eris-keys server --host 0.0.0.0 --log 3]     4767/tcp
                                                                                                                                  
iMac:~ dave$ eris chains new test_chain --dir ~/.eris/chains/test_chain
iMac:~ dave$ eris chains ls
CHAIN          ON     CONTAINER ID     DATA CONTAINER
test_chain     *      cbab659c6c       6d9f628c73
```

Looks like it will impact anyone who uses virgin media DNS servers in the UK.

**Comment by zramsay** [comment] 2016-07-04 16:29
Awesome! Glad it works now :)

**Comment by zramsay** [comment] 2016-07-04 17:29
@dave-ct there may actually be a simpler way to accomplish this without you having to manually change your local configurations. you can try by adding `dns = [ "8.8.8.8" ]` here:

```
[service]
image = "quay.io/eris/keys:0.12.0"
data_container = true
exec_host = "ERIS_KEYS_HOST"
dns = [ "8.8.8.8" ]
#restart = "always"
```
and restarting keys. this will explicitly over-ride `/etc/resolv.conf`

**Comment by dave-ct** [comment] 2016-07-04 19:37
@zramsay thanks for the suggestion,  have tried the above but it is still tries to call an external IP.

```
iMac:~ dave$ eris chains make test_chain --chain-type simplechain
Could not connect to eris-keys server. Start it with `eris services start keys`. Error: Post http://keys:4767/gen: dial tcp 81.200.64.50:4767: i/o timeout
Container interactive-d5c2f7c1-adff-477a-b3b3-4c80a0bea981 exited with status 1
```

Looks like it is not the container the keys service is running in but when I run the command `eris chains make test_chain --chain-type simplechain` This seems to do a post to do `post http://keys:4767/gen` which then gets resolved  by DNS but perhaps that performed outside of the container so setting the container DNS has no impact?  Still learning Eris so that statement may be completely wrong....

**Comment by pietv** [comment] 2016-07-04 19:58
@dave-ct thank you for checking this. can you please try to put that setting in the `~/.eris/chains/default.toml` file. That would change the DNS in the chains container instead of keys' one?
```
[service]
dns = [ "8.8.8.8" ]
```
Thanks.

**Comment by dave-ct** [comment] 2016-07-04 20:29
@pietv have tried the change in the suggested default file but still get the same issue.

```
iMac:~ dave$ eris chains make test_chain --chain-type simplechain
Could not connect to eris-keys server. Start it with `eris services start keys`. Error: Post http://keys:4767/gen: dial tcp 81.200.64.50:4767: i/o timeout
Container interactive-78805a3d-96b7-419c-8955-e9e608bdd135 exited with status 1
```
Here is the updated default.toml 
```
iMac:chains dave$ pwd
/Users/dave/.eris/chains
iMac:chains dave$ cat default.toml 
# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# Service definition file for an eris:db chain.
# Requires Version (handled by eris-cli).

[service]
image          = "quay.io/eris/erisdb:0.12.0"
data_container = true
ports          = [ "1337", "46656", "46657" ]
entry_point    = "erisdb-wrapper"
dns            = [ "8.8.8.8" ]

[dependencies]
services = [ "keys" ]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

```

**Comment by pietv** [comment] 2016-07-04 20:52
@dave-ct thanks very much for your experiment. the `default.toml` file looks correct.
A couple of follow-up questions: are you positive that you have removed the chain completely before starting it anew with the `dns` setting? It has to be done because if it's simply stopped, it will reuse the settings from the already created container.

Also, when you run these commands, do you see the DNS server you specified?
```
$ eris chains inspect simplechain HostConfig.Dns
[8.8.8.8]

$ eris chains exec simplechain cat /etc/resolv.conf
nameserver 8.8.8.8
```
If you do see, then the recipe didn't help. This is definitely a bug (though not frequent), but need to set up a local DNS server to properly reproduce it). @zramsay or I will chat you shortly. Thanks!

**Comment by dave-ct** [comment] 2016-07-04 21:20
@pietv have made sure that it was removed.  Still get the error.  Here is the terminal output including the commands showing the DNS has been updated to 8.8.8.8 from the default.toml in the test_chain container

```
iMac:chains dave$ eris chains rm -xf test_chain
iMac:chains dave$ eris services start keys
iMac:chains dave$ eris chains make test_chain --chain-type simplechain
Could not connect to eris-keys server. Start it with `eris services start keys`. Error: Post http://keys:4767/gen: dial tcp 81.200.64.50:4767: i/o timeout
Container interactive-50f6ee2e-a75a-4131-afe7-29c315c271fa exited with status 1
iMac:chains dave$ eris chains new test_chain --dir ~/.eris/chains/test_chain
iMac:chains dave$ eris chains inspect test_chain HostConfig.Dns
[8.8.8.8]
iMac:chains dave$ eris chains exec test_chain cat /etc/resolv.conf
nameserver 8.8.8.8

```

**Comment by pietv** [comment] 2016-07-15 20:17
@dave-ct I was experimenting a little with this issue by setting up a test DNS with the "keys" entry in it and found that along with DNS settings (explicit or implicit), the "keys" host in `/etc/hosts` is also always present (that's Docker "link" functionality), and that hosts entry will always supersede any DNS settings, something like:
```
127.0.0.1	localhost
...
172.17.0.2	keys 1010eb7d5e84 keys-8b0a814d-bbbf-45a9-a543-fbc054c3d188
172.17.0.3	73101edbe4f2
```
So that wasn't an issue with starting a chain and that's why `dns` config entries didn't work: I didn't pay attention to your initial message which says that the failure is with the `chains make` and not `chains new` which usually fails most of the time, sorry.

Unlike `chains new`, the `chains make` command runs a container without setting any "links" to fix the "keys" host in the `/etc/hosts` file and it doesn't use settings in `~/.eris` directory so the code has to be modified to make a fix.

The fix for this issue is to explicitly set Google DNS servers for `chains make`. The fix is in the #explicit-dns-eris-cm branch of this repo. If you feel like it, you can test the branch to check if it fixes the issue for you, otherwise I'll merge it into the #develop branch in a couple of days. Thanks!

**Comment by pietv** [comment] 2016-07-27 23:14
@dave-ct I'm closing this ticket for now. Please, feel free to reopen if you see this issue again.

**Closed by pietv** 2016-07-27 23:14 UTC
Labels: type/bug

**Comment by joluHo** [comment] 2016-10-25 16:59
@pietv I'm experiencing the same issue in develop branch:
```
 $ eris chains make marketCloud --account-types=Root:1,Developer:2,Validator:5,Participant:20                                                      Could not connect to eris-keys server. Start it with `eris services start keys`. Error: Post http://keys:4767/gen: dial tcp 192.168.0.254:4767: getsockopt: connection refused

Container interactive-ae83f66a-7679-499a-a3e6-dc92bb44af66 exited with status 1
```
```
 eris services exec keys -p "cat /etc/hosts"
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      keys ab4361266cf2 keys-196336f2-3c97-435a-97f1-fa347c1cad93
172.17.0.3      489d7df8ae34
```

**Comment by pietv** [comment] 2016-10-25 17:10
@joluHo thank you for reporting this issue. Yes, that was a Docker API related error we experienced some months ago. The line of code which solves it isn't in the code base right now (we might have considered it fixed). I will put the fix back and ask you to kindly run your test again. Thank you!

**Comment by pietv** [comment] 2016-10-25 17:32
@joluHo the fix appears to have never made it into the master code base, so you might be the first one to test it.

**Comment by joluHo** [comment] 2016-10-27 01:19
@pietv I realized the error is due to the contents of the resolv.conf, but I'm not shure what is modifying it. When I put the correct values on the resolv.conf the issue dispears until the resolv.conf is changed again by some misterious reason (which probably has nothing to do with eris-cli).

**Comment by pietv** [comment] 2016-10-27 14:26
@joluHo yes, the `resolv.conf` file contents are inherited by the Docker containers from your host. The fix does I mentioned overrides your host's DNS servers with Google DNS ones. If by the changed `resolv.conf` you mean the one on the host (the machine you're running Eris CLI from) then no, CLI doesn't change that. It is likely done by your DHCP client settings, if you're on Linux you may check `man dhclient.conf`.
