### ISSUE TITLE
Eris chains logs don't work

### ISSUE THREAD

**Issue by redaz24** [eris-ltd/eris-cli#1151] opened 2016-12-20 10:31 UTC
- [ 1.12.5] `docker version`
- [ 0.12.0] `eris version`
- [ linux ] operating system details (osx/windows/linux)

I'm having some issues with the logs, in fact i followed all the steps for creating multiple instance for one chain and when i want to look at my chain logs i have an error:

"administrator@soptfpas01:~/.eris/chains$ eris chains logs my_tests -f
Failed to read non-empty string for genesis file from config."

I have been working on this for a while and its the first time i see this error so im not sure what i can do.

Thank you very much for your help.

**Comment by pietv** [comment] 2016-12-20 10:40
hi @redaz24, thanks for reporting the issue. Do you see your chain running when issuing the `eris ls` command (`ON`=`*`)? Also, could you please attach the debug logs of the `eris chains logs` command by running it with the `-d` flag.

Also, could you take a look at the `genesis.json` file in the directory of your chain, whether it is empty (`ls ~/.eris/chains/my_test/genesis.json`)? Thank you!

**Comment by redaz24** [comment] 2016-12-20 10:48
Hi @pietv thanks for answering this quickly. Actually my chain is not running ( ON = - ). This is what i get when i run the logs with -d : 
administrator@soptfpas01:~$ eris chains logs my_tests -d
Checking Linux Docker socket                  unix:///var/run/docker.sock
Connecting to Docker                          unix:///var/run/docker.sock
Chain definition loaded            chain name=my_tests
                                                  cmd=
                                                  entrypoint=
                                                   environment=[]
Getting logs                                  my_tests-adbc1356-9bf9-41a1-9c09-c4226868994d
                                                      follow=false
                                                       tail=150
Failed to read non-empty string for genesis file from config.

Finally, my genesis.json file is not empty, i have the adresses of the accounts and their pub_key.

Thank you

**Comment by pietv** [comment] 2016-12-20 11:01
@redaz24 thank you for running this test! Could you please check one more thing: do you see the line `genesis_file` under `[chain]` in the `~/.eris/chains/my_tests/config.toml` file, and whether it equals ""?
Also do you remember the parameter you gave to the `eris chains make` command, did you use it with `--wizard` or `--known` flags? Thanks!

**Comment by redaz24** [comment] 2016-12-20 11:07
@pietv Actually in the config.toml file there isn't any genesis_file:
administrator@soptfpas01:~/.eris/chains/my_tests/my_tests_full_000$ cat config.toml 
# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# It is used to initialize a new eris:db node.
# For more info about the various options, 
# see https://github.com/eris-ltd/mint-client (mintgen).

moniker = "defaulttester.com"
seeds = "10.112.50.191:46656,10.112.50.192:46656,10.112.50.193:46656,10.112.50.194:46656"
fast_sync = false
db_backend = "leveldb"
log_level = "debug"
node_laddr = "0.0.0.0:46656"
rpc_laddr = "0.0.0.0:46657"
vm_log = false

For the eris chains make : eris chains make --account-types=Full:4 my_tests

**Comment by pietv** [comment] 2016-12-20 11:35
@redaz24 thank you for that!

@benjaminbollen @silasdavis any idea why the CM might not properly generate the `config.toml` (missing `[chain]` section) on `eris chains make --account-types=Full:4 my_tests`? I wasn't able to reproduce it (0.12.0 #master).

**Comment by redaz24** [comment] 2016-12-20 11:39
Thanks guys, is this because of some new modifications because i remember doing the same thing a few months ago and it was working pretty fine, i have the commit (002c63e) version of eris, do i need to use a previous release ? 

Thank you for your time guys

**Comment by pietv** [comment] 2016-12-20 11:48
i personally don't think this due to new modifications, and the `002c63e` is the correct (master) version, and it's the one we consider stable. But I haven't seen this error before and this might be potentially a bug to be fixed in further releases. My colleagues might have see this before, that's why I asked them to have a look.

If it isn't too much trouble for you, could you try to recreate your chain from scratch, if this is reproducible for you? (By doing `eris chains rm -rfx my_test` then `eris init` and `eris chains make`, `eris chains start`).

Thanks!

**Comment by redaz24** [comment] 2016-12-20 12:57
Yes of course, ill try to do it again now and see what will happen. Please keep me posted if there is any new information, I will do the same. 

Thanks

**Comment by zramsay** [comment] 2017-01-02 16:28
@redaz24 did the debugging provided by Peter help at all?

**Comment by redaz24** [comment] 2017-01-03 08:24
@zramsay yes the information provided by peter was very helpful, i could finally see the logs, thank you very much

**Closed** 2017-01-03 17:16 UTC
Labels: triaged
