### ISSUE TITLE
setupChain error

### ISSUE THREAD

**Issue by slowtokyo** [eris-ltd/eris-cli#141] opened 2015-08-20 01:41 UTC
On OSX running through Docker Toolbox. Just downloaded the new Eris-CLI release. 

Tried to run a new chain using ```eris chains new shinkansen -d``` and it returned the below.

    Connecting to the Docker Client via: tcp://192.168.99.100:2376
    Docker Certificate Path: /Users/MacBookAir/.docker/machine/machines/default
    Successfully connected to Docker daemon
    Found Eris Container =>		eris_data_shinkansen_1
    Creating Data Container for =>	shinkansen
    Parsing Containers =>		eris_data_shinkansen_1:true
    Container Found =>		/eris_data_shinkansen_1
    Container Found =>		eris_data_shinkansen_1
    Data container exists. Not creating.
    Tragic! Our marmots encountered an error during setupChain for eris_chain_shinkansen_1.
    They also failed to cleanup after themselves (remove containers) due to another error.
    First error =>		stat /home/eris/.eris: no such file or directory
    Cleanup error =>	Unable to load the chain's config for shinkansen in /Users/MacBookAir/.eris/blockchains.
    Check your known chains with:
    eris chains known

The command ```eris chains known``` returns a blank. I can see the data container running in kitematic. 

I had some previous releases of Eris-ware on this comp and I'm wondering if there is a conflict somewhere?

**Comment by compleatang** [comment] 2015-08-20 10:59
Slow. Try removing ~/.eris and then rerun `eris init`. It should drop the relevant config file then. 

If it doesn't drop them then try `eris init -p` and let us know, we'll make the appropriate changes.

**Comment by slowtokyo** [comment] 2015-08-20 14:43
Hiya, looks like this didn't solve the problem unfortunately.

**Comment by slowtokyo** [comment] 2015-08-20 15:01
Seems there is no chains definition file in the ```~.eris/ folder```. Is that supposed to be populated via ```eris init```?

**Comment by zramsay** [comment] 2015-08-20 15:29
Problem found; closing b/c duplicate of #144. Follow it there. Also, @slowtokyo, it should be `~/.eris/` and not `~.eris/`.

**Comment by zramsay** [comment] 2015-08-21 14:59
actually, this error is different. so far I've been unable to replicate it. following `eris init` does nothing appear in `~/.eris/`?

**Comment by zramsay** [comment] 2015-08-21 20:24
replicated it by running the tests.

**Comment by slowtokyo** [comment] 2015-08-22 00:38
Roger on the replicate. the folder contents are as attached.
![image](https://cloud.githubusercontent.com/assets/8579773/9421615/7f5cc0f0-48b1-11e5-9840-4d7809aba093.png)

**Comment by compleatang** [comment] 2015-08-25 22:03
We've pushed some major updates to the chains starting sequence and bolstered our tests. Gonna close this for now, but please reopen if it returns.

**Comment by slowtokyo** [comment] 2015-08-26 21:27
Hi guys. Still unfortunately getting the same error. 

I thought it might have something to do with my docker installation, so I [uninstalled everything] (https://docs.docker.com/installation/mac) and reinstalled, which gave me the following error.

```
bash-3.2$ eris chains new test
Pulling image (eris/data) from repository. This could take a second.
Error creating data containr =>	Post https://192.168.99.100:2376/containers/create?hostconfig=%7B%22RestartPolicy%22%3A%7B%7D%2C%22LogConfig%22%3A%7B%7D%7D&name=eris_data_test_1: http: can't write HTTP request on broken connection
```
Followed by...
```
bash-3.2$ eris chains new test
Tragic! Our marmots encountered an error during setupChain for eris_chain_test_1.
They also failed to cleanup after themselves (remove containers) due to another error.
First error =>		stat /home/eris/.eris: no such file or directory
Cleanup error =>	Unable to load the chain's config for test in /Users/MacBookAir/.eris/blockchains.
Check your known chains with:
eris chains known
```

**Comment by compleatang** [comment] 2015-08-28 11:24
Just to confirm @slowtokyo you're on master branch for Eris? The changes we're talking about will be pushed to master today or over the weekend, they're currently on develop.

**Comment by compleatang** [comment] 2015-08-30 01:57
Slow when you have time to check, should be fixed now.

**Closed by compleatang** 2015-08-30 01:57 UTC
Labels: completed

**Comment by slowtokyo** [comment] 2015-08-30 10:17
Sorry been traveling a bit recently. Yah, looks like everything works now!

**Comment by compleatang** [comment] 2015-08-30 12:08
:thought_balloon: :tractor: :tada:
