### ISSUE TITLE
Container not starting for existing chain

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-cli#770] opened 2016-06-23 13:27 UTC
I've experienced the following scenario now for several days.
After creating an existing chain and restarting the computer (or docker-machine), the chain cannot be started anymore with `eris chains start`. Creating a new chain (`eris chains new`) still works and so the workaround is to just abandon the other chain, but clearly there is a problem.
At this point there is no clear path to reproduce. It usually happens after a OS restart.

```
$ eris chains start lei -v
Booting chain dependencies             chains=[]
                                     services=[keys]
Starting a chain                              lei
Running container                             lei-7ec54eb5-55b9-4521-9195-ad627a9b9518
Manage data containers?              autodata=true
Data container already exists. Not creating
Starting container                            lei-7ec54eb5-55b9-4521-9195-ad627a9b9518
                                          cmd=[run]
                               data container=lei-143c35d4-e458-40f6-ab73-2a0144be4c3b
                                   entrypoint=[erisdb-wrapper]
                                  environment=[CHAIN_ID=lei ERISDB_API=true]
                                        image=quay.io/eris/erisdb:0.12.0-rc2
                              published ports=false
Container started                             lei-7ec54eb5-55b9-4521-9195-ad627a9b9518

jan at MacBook-Pro-6 in ~
$ eris chains ls
CHAIN     ON     CONTAINER ID     DATA CONTAINER
lei       -      ef4b6f881e       258e4b8a9c
                                                    

jan at MacBook-Pro-6 in ~
$ docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS               NAMES
e8f3165b7ca5        quay.io/eris/keys:0.12.0   "eris-keys server --h"   32 hours ago        Up 10 minutes       4767/tcp            keys-4bd4864f-6f3c-49fb-ae0d-d60b0b26a13b

jan at MacBook-Pro-6 in ~
$ eris version
Eris CLI Version: 0.12.0-rc2
$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
$ docker-machine version
docker-machine version 0.7.0, build a650a40

```

- [x] `docker version`
- [x] `eris version`
- [x] `docker-machine version` (if applicable / !linux)
- [x] operating system details: Mac OS

**Comment by pietv** [comment] 2016-06-24 14:05
@j-h-scheufen on it

**Comment by pietv** [comment] 2016-07-15 22:05
After this PR [#808](https://github.com/eris-ltd/eris-cli/pull/808) has been merged, can't reproduce this error any longer. Please, feel free to reopen if you encounter any issues.

**Closed by pietv** 2016-07-15 22:05 UTC
Labels: os/osx, type/bug

**Comment by infinius12345** [comment] 2016-08-04 16:38
Hi,
I am having the same issue 
infinius@infinius-VirtualBox:~$ eris chains start simplechain -v
The marmots could not find docker-machine installed. While it is not required to use the Eris platform, we strongly recommend it be installed for maximum blockchain awesomeness.
Booting chain dependencies             chains=[]
                                     services=[keys]
Starting a chain                              simplechain
Running container                             simplechain-10954a0e-21df-4207-b636-206e317962f5
Manage data containers?              autodata=true
Data container already exists. Not creating
Starting container                            simplechain-10954a0e-21df-4207-b636-206e317962f5
                                          cmd=[run]
                               data container=simplechain-31cc220f-6b57-49b8-a126-ef0ac28c76f7
                                   entrypoint=[erisdb-wrapper]
                                  environment=[CHAIN_ID=simplechain ERISDB_API=true]
                                        image=quay.io/eris/erisdb:0.12.0-rc2
                              published ports=false
Container started                             simplechain-10954a0e-21df-4207-b636-206e317962f5
infinius@infinius-VirtualBox:~$ eris chains ls
CHAIN           ON     CONTAINER ID     DATA CONTAINER
simplechain     -      c55e1be9cd       5e85b4042c
                                                          
infinius@infinius-VirtualBox:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
a896dd41f8a2        360bda711bfb        "eris-keys server --h"   11 days ago         Up 2 minutes        4767/tcp            keys-b032613e-d385-4cc7-ae24-52e7ecaec6fc

**Comment by zramsay** [comment] 2016-08-10 15:05
Hi @infinius12345 . Does the behaviour persist after you re-run `eris init` ... we had unexpected behaviour with the rc2 images that have now been sorted. Does this behaviour persist with eris version 0.12.0-rc3 (built from source) or on 0.11.4 ?

**Comment by infinius12345** [comment] 2016-08-10 15:16
Hi i started a new thread for this
https://github.com/eris-ltd/eris-cli/issues/850
