### ISSUE TITLE
[PM] Contracts-Path is not passed to EPM

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-cli#954] opened 2016-09-26 23:24 UTC
according to https://github.com/eris-ltd/eris-cli/blob/develop/pkgs/pkgs.go#L349 ```--contracts-path``` is not being passed in. This would explain the problems in https://github.com/eris-ltd/eris-pm/issues/196 as no matter what is passed in, the default contracts path variable is always the output.

**Comment by zramsay** [comment] 2016-09-28 14:59
duplicate of #904

**Closed by zramsay** 2016-09-28 14:59 UTC
