### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by slowtokyo** [eris-ltd/eris-cli#188] opened 2015-08-30 12:08 UTC
Not sure if this is a bug or intentional while under development.

After `eris init` I get the following message

```
bash-3.2$ eris init
The marmots have connected to Docker successfully.
They will now will install a few default services and actions for your use.

Looks like the /Users/MacBookAir/.eris/services directory exists.
Would you like the marmots to pull in any recent changes? (Y/n): Y
fatal: Not a git repository (or any of the parent directories): .git

The marmots have everything set up for you.
If you are just getting started please type [eris] to get an overview of the tool.
```

It looks like the services available in the previous version are no longer available. `eris services known` returns 
```
bash-3.2$ eris services known
do_not_use
ipfs
keys
```

**Comment by compleatang** [comment] 2015-08-30 12:12
Yes. This is a duplicate of #182 will push a fix soon, but in the interim just `rm -rf ~/.eris/services` that will fix it.

**Comment by compleatang** [comment] 2015-08-30 12:12
BTW, do the same with actions.

**Comment by compleatang** [comment] 2015-08-30 12:38
should be fixed now. feel free to reopen if it appears (pull master first though :smile:  )

**Comment by slowtokyo** [comment] 2015-08-30 15:41
Yup. There is no error now. Just to be clear, the only two "ready-made" services out there are the ipfs wrapper and the keys services (haven't really explored the latter yet)?

**Comment by compleatang** [comment] 2015-08-30 15:43
Right. We compile those services into the binary so that if git is not installed on the machine that the user will at least have "something" to work with. If you do `eris services known` now you'll see more than that. The service definition files for what was dropped before and what was pulled in should be exactly the same BTW. So now, you should have more "ready-made" services to use.

**Comment by slowtokyo** [comment] 2015-08-30 16:18
Thanks Casey. I updated just now and here is the output I get. Just ipfs and keys.
```
bash-3.2$ eris version
Eris CLI Version: 0.10.1
bash-3.2$ eris services known
do_not_use
ipfs
keys
```

**Comment by slowtokyo** [comment] 2015-08-30 16:22
btw, I do have git installed on my machine (v. 2.4.5).

**Comment by compleatang** [comment] 2015-08-30 16:25
Hmm. Did you run `eris init` again? The services repo is pulled in during the init sequence. If that doesn't fix it to look something like this:

```
>> eris services known                                                                                                                                    
bitcoinxt
btcd
do_not_use
eth
ipfs
keys
mindy
mint
sandstorm
thel
tinydns
```

Then dump me the output of `eris init -d` cause something super funky is going on.

**Comment by slowtokyo** [comment] 2015-08-30 16:29
After deleting ~./.eris I get the following
```
bash-3.2$ eris init -d
Connecting to the Docker Client via TLS.
	URL =>			tcp://192.168.99.100:2376
	Docker Cert Path =>	/Users/MacBookAir/.docker/machine/machines/default
Initialized empty Git repository in /Users/MacBookAir/.eris/services/.git/
Connected over TLS.Successfully connected to Docker daemon
Setting IPFS Host
Set ERIS_IPFS_HOST to =>	http://192.168.99.100
The marmots have connected to Docker successfully.
They will now will install a few default services and actions for your use.

Root eris directory (/Users/MacBookAir/.eris) already exists. Please type `eris` to see the help.
Adding default files
Chain defaults written.
Using default defs.
Service defaults written.
Action defaults written.
Initialized eris root directory (/Users/MacBookAir/.eris) with default actions and service files.

The marmots have everything set up for you.
If you are just getting started please type [eris] to get an overview of the tool.
```

Just as an FYI maybe related to #182, when I run it the second time I get the fatal error message again. 
```
bash-3.2$ eris init -d
Connecting to the Docker Client via TLS.
	URL =>			tcp://192.168.99.100:2376
	Docker Cert Path =>	/Users/MacBookAir/.docker/machine/machines/default
Connected over TLS.Successfully connected to Docker daemon
Setting IPFS Host
Set ERIS_IPFS_HOST to =>	http://192.168.99.100
The marmots have connected to Docker successfully.
They will now will install a few default services and actions for your use.

Root eris directory (/Users/MacBookAir/.eris) already exists. Please type `eris` to see the help.
Adding default files
Chain defaults written.
The location exists. Attempting to pull instead.
Looks like the /Users/MacBookAir/.eris/services directory exists.
Would you like the marmots to pull in any recent changes? (Y/n): Y
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Using default defs.
Service defaults written.
Action defaults written.
Initialized eris root directory (/Users/MacBookAir/.eris) with default actions and service files.

The marmots have everything set up for you.
If you are just getting started please type [eris] to get an overview of the tool.
```

**Comment by compleatang** [comment] 2015-08-30 16:32
Super. Will look into the second one. Did it clone the services for you?

**Comment by slowtokyo** [comment] 2015-08-30 16:34
Ah, and the output of the services known command is still not showing the rest.
```
bash-3.2$ eris services known
do_not_use
ipfs
keys
```

**Comment by slowtokyo** [comment] 2015-08-30 16:39
I'm questioning whether I am actually running the latest version. The process I used to delete/reload Eris is: 
1) delete directory ~./.eris
2) delete directory ~./go (the $GOPATH)
3) delete the VM
4) boot up Kitematic
5) run `go get github.com/eris-ltd/eris-cli/cmd/eris`
6) run `eris init`

Does that sound right?

**Comment by compleatang** [comment] 2015-08-30 16:41
Hmmm. It does sound correct (and we have an issue to make that easier). Generally speaking shouldn't need to delete the `.eris` dir, but if nothing in there then no problem. 

What commit are you on? `cd $GOPATH/src/github.com/eris-ltd/eris-cli && git rev-parse --verify HEAD` (current master is 702f353e5f2e7bd9c42ed29ea963d1f0a760672d). If you're on a different commit then just git pull and `go install` from the `cmd/eris` directory. That said, if you just did that then `go get` should have checkedout that master and something else is going on.

It seems like it init'ed the git directory in services but somehow didn't get to add the git remote step. Which is in the same function and it should complain if it didn't get to it.

**Comment by slowtokyo** [comment] 2015-08-30 16:43
Seems I'm on the right commit. 
```
bash-3.2$ cd $GOPATH/src/github.com/eris-ltd/eris-cli && git rev-parse --verify HEAD
702f353e5f2e7bd9c42ed29ea963d1f0a760672d
```

**Comment by compleatang** [comment] 2015-08-30 17:27
Then something else is going on; will investigate. For now anyone can just manually clone the eris-services repo into ~/.eris/services if you need a quick fix.

**Comment by slowtokyo** [comment] 2015-08-30 17:28
Thanks as always. Will do.

**Comment by compleatang** [comment] 2015-09-01 00:16
Pretty sure we fixed this today as others are reporting success on current master.

**Closed** 2015-09-01 00:16 UTC
Labels: completed
