### ISSUE TITLE
`npm install` fails in contracts interacting tutorial

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#551] opened 2016-03-05 20:18 UTC
I am running into an issue with the first step of the [contracts interaction tutorial](https://docs.erisindustries.com/tutorials/contractsinteracting/#tocAnchor-1-3) on Ubuntu 14.10 at digital ocean.

### In brief
The node.js install link that you post is not really working, since for now we're anyway pretty much all on Ubuntu I would suggest to install node.js and npm with a simple
```
sudo apt-get update
sudo apt-get install nodejs-legacy
sudo apt-get install npm
```
instead of linking that site with instructions that do not really work for the current default system.

### Long story
First I installed node 5.7.1 [as described on the link that you post](https://github.com/nodesource/distributions#debmanual):
```
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install -y nodejs
node --version
v5.7.1
```
Then trying to run my node package that has been created in the tutorial I get an error:
```
root@ContractInteraction:~/.eris/apps/idi# npm install

> bufferutil@1.2.1 install /root/.eris/apps/idi/node_modules/bufferutil
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:87:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:98:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.13.0-79-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.eris/apps/idi/node_modules/bufferutil
gyp ERR! node -v v5.7.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install /root/.eris/apps/idi/node_modules/utf-8-validate
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:87:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:98:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.13.0-79-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.eris/apps/idi/node_modules/utf-8-validate
gyp ERR! node -v v5.7.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
npm WARN idis_app@0.0.1 No description
npm WARN idis_app@0.0.1 No repository field.
npm WARN idis_app@0.0.1 No license field.
```

despite not being on AWS but DO, I am running the install for the alternative npm version but also this runs into issues:
```
root@ContractInteraction:~/.eris/apps/idi# sudo apt-get install --yes git nodejs-legacy npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version.
git set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nodejs-legacy : Depends: nodejs (>= 0.6.19~dfsg1-3~) but it is not going to be installed
 npm : Depends: nodejs but it is not going to be installed
       Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
       Depends: node-ansi but it is not going to be installed
       Depends: node-archy but it is not going to be installed
       Depends: node-block-stream but it is not going to be installed
       Depends: node-fstream (>= 0.1.22) but it is not going to be installed
       Depends: node-fstream-ignore but it is not going to be installed
       Depends: node-github-url-from-git but it is not going to be installed
       Depends: node-glob (>= 3.1.21) but it is not going to be installed
       Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
       Depends: node-inherits but it is not going to be installed
       Depends: node-ini (>= 1.1.0) but it is not going to be installed
       Depends: node-lockfile but it is not going to be installed
       Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed
       Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
       Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
       Depends: node-gyp (>= 0.10.9) but it is not going to be installed
       Depends: node-nopt (>= 2.1.1) but it is not going to be installed
       Depends: node-npmlog but it is not going to be installed
       Depends: node-once but it is not going to be installed
       Depends: node-osenv but it is not going to be installed
       Depends: node-read but it is not going to be installed
       Depends: node-read-package-json (>= 1.1.0) but it is not going to be installed
       Depends: node-request (>= 2.25.0) but it is not going to be installed
       Depends: node-retry but it is not going to be installed
       Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
       Depends: node-semver (>= 2.1.0) but it is not going to be installed
       Depends: node-sha but it is not going to be installed
       Depends: node-slide but it is not going to be installed
       Depends: node-tar (>= 0.1.18) but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by zramsay** [comment] 2016-03-05 20:19
cc @NodeGuy

**Comment by compleatang** [comment] 2016-03-06 22:45
@SCBuergel the problem is your underlying packages...

```
stack Error: not found: make
```

try `(sudo) apt-get install make` if that solves the problem then we'll update the tut to make sure folks install make. (if it fails try installing `automake` too)

**Comment by NodeGuy** [comment] 2016-03-10 01:34
This is tricky to recreate because Ubuntu 14.10 is no longer supported by Ubuntu and a fresh installation won't even let me install `npm`.  I suggest you upgrade to a supported version of Ubuntu.

**Comment by SCBuergel** [comment] 2016-03-10 07:44
Sorry my mistake, that was performed on Ubuntu 14.04 which still is supported and the default version for major cloud providers (e.g. digitalocean).

**Comment by NodeGuy** [comment] 2016-03-11 22:05
Installation fails on Ubuntu 14.04 LTS because it has an outdated version of `npm`.  To upgrade `npm`, follow these steps:

```shell
sudo apt-get update
sudo apt-get install --yes git nodejs-legacy npm
sudo npm install --global npm
hash -r
```

**Comment by compleatang** [comment] 2016-03-13 13:12
Seb, I've updated the tut to reflect Dave's words above. Closing for now but feel free to reopen if that doesn't fix the issue for you.

**Closed by compleatang** 2016-03-13 13:12 UTC
Labels: area/documentation
