### ISSUE TITLE
eris pkgs needs chain directory in current dir

### ISSUE THREAD

**Issue by rguikers** [eris-ltd/eris-cli#994] opened 2016-10-12 14:17 UTC
tested on version 0.12RC3

`eris pkgs do`
expects the chain directory in its path. Got a message
`eris pkgs do --chain ppu --address 636EF5823E082AD66EBC203FD4DFB1031F0C61CA --file ../server/contracts/epm.yaml -p ../server/contracts`
`Performing action. This can sometimes take a wee while
Cannot start a chain I cannot find`

when running in a directory where there is no child directory containing the chain (ppu in this case) it fails. 
when running the command where the ppu directory is a child dir, it runs fine..

**Comment by zramsay** [comment] 2016-10-13 14:54
thanks for the bug report. Currently investigating. 

As an aside, I see that the `--contracts-path` (`-p`) flag works/has worked for you. @j-h-scheufen did you ever get that working? related to #904 & related epm issues

**Comment by zramsay** [comment] 2016-11-07 19:25
Closing as resolved - could not reproduce & the issue looks be a duplicate of #904

**Closed by zramsay** 2016-11-07 19:25 UTC
Labels: area/pm, bug/confirmed
