### ISSUE TITLE
Key service ports are not mapped

### ISSUE THREAD

**Issue by rguikers** [eris-ltd/eris-cli#778] opened 2016-07-03 12:07 UTC
Please include in your bug report:

Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64- [ ] `eris version`
el capitan osx

Eris CLI Version: 0.12.0

problem :
`eris services start keys`
would expect that port 4767 is mapped as default, but it is not.
only method to map ports is by using the --publish flag, but is a random port.

Especially when we use `eris chains new default` there is no standard way to get to the key server by fi. curl.

Don't really know if this is a bug or by design. If by design, it would be a nice feature to have some control over the key server port. (especially with the new erisdb.js version which relies on an open port for the key server)

Thanks,

**Comment by pietv** [comment] 2016-07-03 12:37
Hi @rguikers.

You can make an entry to a `~/.eris/services/keys.toml` definition file to publish that port:
```
ports = [ "4767:4767" ]
```
Please, try that.

I understand by mapping you mean exposing and publishing the port to the host system. This port is exposed only to the chains containers now, not the host system. Why do you expect it be mapped to the host?

**Comment by rguikers** [comment] 2016-07-03 13:12
Thanks Peter, will add the ports variable to the toml file. Reason for using this is the ability to sign transactions through RPC or http calls. Also the erisdb.js master branch is expecting a mapped port for keys to set permissions and sign transactions. Don't know if there is another way to use it for this functionality..

Thanks,

**Comment by pietv** [comment] 2016-07-03 13:14
If your the erisdb.js independently outside Docker container then you need the keys port exposed. Gotcha, thanks. (But right now it's not and it is by design.)

**Comment by rguikers** [comment] 2016-07-04 07:58
Hi Peter, 

Isn’t erisdb.js not something you typically use in an application outside the docker containers (or outside the eris docker machine)?, or is the idea to run all interfaces to erisdb in docker containers (and in the same docker machine) as well?
Just curious about this.
In my opinion you should be able to sign transactions outside the docker environment, but interested in how you look at this.

One extra thing i’m trying to figure out is that after adding the port mapping to the keys.toml (ports = [ "4767:4767" ]) the command `eris services exec keys -i` is  failing with “port is already allocated”. Seems that the exec command is trying to re-assign the ports again. "docker exec -it … bash” is running fine however.

Thanks,

**Comment by pietv** [comment] 2016-07-04 08:26
Hi Rob, the concern for not exposing the keys port is security: it should be linkable (visible) to chains containers but shouldn't be available to the outside world. Maybe @NodeGuy could better explain this and answer your question about the possibility of signing transactions outside the docker environment (but outside docker environment the keys server won't run in a Docker container either and will bind the network port and it will be visible to erisdb.js).

Answering your question about the published port:
> Seems that the exec command is trying to re-assign the ports again

Yes, this behaviour is due to the `exec` command is using the same settings from the `keys.toml` file and is trying to bind the same port. You can either run the `exec` command with the `-p` or `--ports` flags or create an alternative `keys2.toml` something file with `ports = [ ]` setting removed from it. (The issue is that you can't have 2 containers publishing the same port.)

**Comment by rguikers** [comment] 2016-07-04 18:46
Thanks Peter, will wait for the implementation of the latest erisdb.js and see how this will communicate with its environment.

**Comment by compleatang** [comment] 2016-07-07 00:47
closing as fixed on cli side.

**Closed by compleatang** 2016-07-07 00:47 UTC
Labels: type/change default

**Comment by NodeGuy** [comment] 2016-07-07 01:26
Peter's point is that if you run your client application in a container then you have more control over who has access to the Eris Keys port than if it's mapped to your Docker host.  I wouldn't worry about it too much for now.
