### ISSUE TITLE
EPM should not reload the contract files.

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-cli#827] opened 2016-07-28 00:00 UTC
In a text editor, when running epm, any changes to the contract files that are used in the test are lost when epm finishes. It seems a file reload is occurring.

OSX version: 10.11.5
Eris CLI Version: 0.12.0-rc2
Docker:
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
docker-machine version 0.7.0, build a650a40

**Comment by compleatang** [comment] 2016-08-22 14:12
duplicate of #539 closing this issue.

**Closed by compleatang** 2016-08-22 14:12 UTC
Labels: status/rejected
