### ISSUE TITLE
Problem with docker-machine-version compatibility testing

### ISSUE THREAD

**Issue by mvaz** [eris-ltd/eris-cli#700] opened 2016-05-09 13:11 UTC
Dear all,
I was following the introductory steps, and ran into a problem, after doing
```
docker-machine create marmot1 --driver virtualbox
eval "$(docker-machine env marmot1)"
eris init
```
The error message was 
```
Eris requires docker-machine version >= 0.6.0
The marmots have detected version: docker-machine version 0.7.0
Come back after you have upgraded and the marmots will be happy to service your blockchain management needs
```

Afterwards I've downgraded the docker version to 0.6.0 (both versions were installed with the DockerToolbox) and got the following error
```
Eris requires docker-machine version >= 0.6.0
The marmots have detected version: docker-machine version 0.6.0
Come back after you have upgraded and the marmots will be happy to service your blockchain management needs
```
What can I do to correct this?
Thanks in advance
MV

Further info:
- [0.7.0] `docker version`
- [0.11.4] `eris version`
- [Windows 7 Enterprise SP1]

**Comment by pietv** [comment] 2016-05-09 13:14
Hi @mvaz! Thanks for reporting the issue. We'll try to reproduce it return to you with a fix shortly.

**Comment by pietv** [comment] 2016-05-10 01:39
@mvaz i was trying to reproduce the issue on Windows 10 and Windows 7 (on the VM), with the CMD, Cygwin and git bash (Docker Toolbox) shells with Docker Machine 0.70 — everything works for me without issues. 

The recipe for the Windows 7 after clean install:
1) install Go for Windows, 
2) install Git for Windows, 
3) Install Docker Toolbox,
4) Wait for the DM to be created.
5) git clone https://github.com/eris-ltd/eris-cli; go get ./cmd/eris
6) eris init

I didn't attempt to create the "marmot1" machine, I assumed the "default" machine doesn't work for you either (does it?) Also, I used the Windows 7 Home not the Enterprise variant.

Could you please kindly check that you're using the latest #master commit (`git pull origin master`) not the older #develop version (0.11.4 used to be #develop until very recently, now it is #master).

I'd like to also ask you if you can send the debug output for the init command: it may contain further clues for the issue:
```
$ eris init -d
```
Thanks!

Also, are you able to try the CMD shell for your experiments as opposed to Docker Toolbox?

Other possible solutions: using a more recent Windows OS version in an Amazon EC2 instance, I can share an invite for the https://beta.docker.com where Docker can run on Windows without a Docker Machine.

**Comment by AFDudley** [comment] 2016-05-10 01:47
@mvaz Is there more than one docker-machine installed on your computer?

**Comment by u14395283** [comment] 2016-05-10 12:56
I seem to have the same problem - currently running it on Windows 10. Also installed with the toolbox. And the newest release from Eris (but I didn't build from source).
This is my debug data:
`$ eris init -d
Getting connection details from environment
                                    [3241mcert path[0;10m=[1mC:\Users\Me\.docker\machine\machines\default[0;10m
                                         [3241mhost[0;10m=[1mtcp://192.168.99.100:2376[0;10m
Getting connection details from Docker Machine
                                      [3241mmachine[0;10m=[1meris[0;10m
                                    [3241mcert path[0;10m=[1mC:\Users\Me\.docker\machine\machines\default[0;10m
                                         [3241mhost[0;10m=[1mtcp://192.168.99.100:2376[0;10m
Connecting to Docker via TLS        [3241mcert path[0;10m=[1mC:\Users\JoDan\.docker\machine\machines\default[0;10m
                                         [3241mhost[0;10m=[1mtcp://192.168.99.100:2376[0;10m
Connected via TLS
Successfully connected to Docker daemon
Setting ERIS_IPFS_HOST                    [3241murl[0;10m=[1mhttp://192.168.99.100[0;10m
Eris requires docker-machine version >= 0.6.0
The marmots have detected version: docker-machine version 0.6.0
Come back after you have upgraded and the marmots will be happy to service your blockchain management needs`

**Comment by mvaz** [comment] 2016-05-10 12:57
@AFDudley  no, only one

**Comment by thePhantomCupcake** [comment] 2016-05-10 13:16
Also have this problem on Windows 10.

**Comment by pietv** [comment] 2016-05-10 13:23
@u14395283 @thePhantomCupcake thank you for your reports! I've just tested the binary release on Windows 10 and it works as expected.

From the debug output I can guess with some certainty what the issue might be. I'll prepare a fix and hope you would be kind enough to test the fix on your machines. I will then merge the hotfix to #master. Thanks.

**Comment by thePhantomCupcake** [comment] 2016-05-10 13:25
@pietv Awesome, thanks,will be more than willing to test.

**Comment by mvaz** [comment] 2016-05-10 15:21
@pietv I've reinstalled everything in that order and the problem persists. I used the Docker Toolbox and afterwards cmd...
Not sure how to go about this, but willing to try docker beta.

**Comment by pietv** [comment] 2016-05-10 15:30
@mvaz sorry to hear it. yeah, a bit puzzling that it does work for me... please, give me a short while to fix it. Thank you!

**Comment by pietv** [comment] 2016-05-10 15:37
@mvaz sent you a Beta Docker invitation code.

**Comment by mvaz** [comment] 2016-05-10 16:06
@pietv thanks. will give it a go.

**Comment by pietv** [comment] 2016-05-10 16:09
Excellent :+1: Please, after you install the Beta Docker, update your #master with `go get -u` - I've just merged something to support it. Thank you.

**Comment by pietv** [comment] 2016-05-11 10:32
@mvaz @thePhantomCupcake @u14395283 The fix for this issue is now in the `fix-dm-windows` branch. Please test when you feel like it. 

You will need to have it built from source: install Go ([https://golang.org/dl/](https://golang.org/dl/)) and set `GOPATH` (anywhere, usually `C:\`) and `GOBIN` (somewhere your PATH points to) environment variables and then run:

```
$ git clone https://github.com/eris-ltd/eris-cli
$ git fetch origin fix-dm-windows
$ git checkout fix-dm-windows
$ cd eris-cli/cmd/eris
$ go install

$ eris version
$ eris init
```

Please let me know if that worked for you, I will then merge the branch to #master.

Thanks!

**Comment by pietv** [comment] 2016-05-16 06:13
Merged to #develop.

**Comment by xiaoxiaofangyu** [comment] 2016-05-19 17:10
Hi, how could I get fix-dm-windows from #develop branch?

**Comment by pietv** [comment] 2016-05-19 18:18
hi, it would be just #develop instead of #fix-dm-windows in the above recipe:
```
$ git clone https://github.com/eris-ltd/eris-cli
$ git fetch origin develop
$ git checkout develop
$ cd eris-cli/cmd/eris
$ go get
$ go install

$ eris version
$ eris init
```
Please, let me know if that works for you!

**Comment by xiaoxiaofangyu** [comment] 2016-05-19 19:50
Thanks, successfully fetch develop, and then go get and go install.  However, ran into the same docker-machine incompatible error message when eris version.

**Comment by pietv** [comment] 2016-05-19 20:16
Thanks for checking that! Can you check that the binary you installled is the one you compiled? `eris` path is in `GOBIN` (Docker Toolbox `which eris`)? And then `go clean -i` and `go install`?

**Comment by xiaoxiaofangyu** [comment] 2016-05-19 22:22
eris is in GOBIN, and go clean before go install.  However, the same incompatible error message.

**Comment by pietv** [comment] 2016-05-20 04:43
Thank you for checking that! I've compiled a binary for the #develop branch, it is here: https://github.com/eris-ltd/eris-cli/releases/download/v0.11.4/eris_0.12.0_develop_windows_amd64.zip Could you please try running that on your machine to see if you're still seeing that error (to avoid any possible `git` problems if any).

If you will see that error, please could you paste it again (to be certain that it is still the same error).

Thank you and sorry for all the trouble!
Thank you and sorry for all

**Comment by pietv** [comment] 2016-05-23 16:37
Binary build is confirmed to have fixed the issue on Windows 10 with Babun shell (for reference: Freshdesk ticket 292).

Will cherry-pick the fix into #master in a couple of days.

**Comment by pietv** [comment] 2016-05-24 18:10
Merged to #master

**Comment by pietv** [comment] 2016-05-30 10:54
Closing for now. Please reopen if the issue persists.

**Closed by pietv** 2016-05-30 10:54 UTC
Labels: area/docker-machine, area/shell integration, os/windows, type/bug

**Comment by AFDudley** [comment] 2016-06-11 14:16
@compleatang I just ran into this bug, we should consider doing hotfixes since right now naive windows users still hit this bug.
