### ISSUE TITLE
INTERNAL_ERROR when accessing array out of bounds

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#678] opened 2016-04-27 11:57 UTC
When attempting to read an array outside of its bounds in solidity, I run into the following RPC error:
```
[JSON RPC 2.0 Error] Message Id: 2, (INTERNAL_ERROR) - Invalid jump dest
Error callback from sendTransaction
[Error: Invalid jump dest]
```

I think this scenario should handled a bit more gracefully. Below my contract and node.js code, I am running the latest Eris 0.11.3 installed from binary via github, running on Ubuntu 14.04.

---

contract:
```
contract test
{
  int[] test;

  function add(int num)
  {
    test.push(num);
  }

  function get(uint index) constant returns (int x)
  {
    return (test[index]);
  }
}
```

interfaced via the following app.js:
```
var fs = require('fs');
var erisC = require('eris-contracts');
var erisdbURL = "http://localhost:1337/rpc";

var contractData = require('./epm.json');
var contractAddress = contractData["deployTestContract"];
var testAbi = JSON.parse(fs.readFileSync("./abi/" + contractAddress));

var accountData = require('./accounts.json');
var contractsManager = erisC.newContractManagerDev(erisdbURL, accountData.simpl$
var contract = contractsManager.newContractFactory(testAbi).at(contractAddress);

console.log('contract interface setup.');
contract.add(1, function(error, result){
  if (error) { console.log(error) }
  else { console.log('added 1') }
});

contract.get(100, function(error, result){
  if (error) { console.log(error) }
  else {
    var val = result.toNumber();
    console.log('value: ' + val);
  }
});
```

**Comment by zramsay** [comment] 2016-04-27 14:48
@VoR0220 are you able to replicate this?

**Comment by zramsay** [comment] 2016-04-27 14:50
oh, i misread. this isn't a bug, correct? what would you rather see as an error message?

**Comment by SCBuergel** [comment] 2016-04-27 15:09
I would expect a normal solidity exception with all the consequences. I don't see why this should be raising an RPC exception. Therefore I would call it a bug.

**Comment by VoR0220** [comment] 2016-04-27 16:35
This is correct behavior. You're calling the blockchain from an RPC client to the blockchain (which kind of acts like a server) in the JS. The JS cannot process the transaction because the solidity code cannot execute because you've run outside the bounds of the array, therefore leading to an invalid jump statement, which is then returned to the JS call. Closing as not a bug.

**Closed by VoR0220** 2016-04-27 16:35 UTC
Labels: type/bug
